### ISSUE TITLE
Question on the compatibility with ubuntu 12.04 and RT Linux

### ISSUE THREAD

**Issue by nonokangwei** [Azure/azure-event-hubs-c#25]
if these SDK works in Ubuntu 12.04 environment and RT Linux ?
Thanks
BR

**Comment by dcristoloveanu** [comment]
Hi @nonokangwei,

Sorry for the delay in answering.
It should definitely be OK to use it with Ubuntu 12.04.
I am not what openssl version is on RT Linux, but if you have an OpenSSL version that is on the system or you can build one for that distribution, it should work, since the code is all C99 code.

Feel free to reopen and let me know in case you still need assistance.

Cheers,
/Dan
